[tools]
aqua = "latest"
croc = "latest"
harper-ls = "latest"
lua = "5.4"
node = "latest"
"npm:@earendil-works/pi-coding-agent" = "latest"
"npm:@pintora/cli" = "latest"
rumdl = "latest"
rust = "latest"
shellcheck = "latest"
stylua = "latest"
tinymist = "latest"
typst = "latest"
shfmt = "latest"
usql = "latest"
xh = "latest"
hurl = "latest"
oxlint = "latest"
"npm:oxfmt" = "latest"
just = "latest"
zellij = "latest"
act = "latest"
oh-my-posh = "latest"
zoxide = "latest"
fzf = "latest"
helix = "latest"
yazi = "latest"
eza = "latest"
lazygit = "latest"
lima = "latest"
colima = "latest"
rg = "latest"
taplo = "latest"
uv = "latest"
"go:github.com/charmbracelet/pop" = "latest"
"go:github.com/maaslalani/invoice" = "main"
television = "latest"
etcd = "latest"
bottom = "latest"
d2 = "latest"
amass = "latest"
herdr = "latest"

[settings]
experimental = true
