#theme = "sleek-transparent"
theme = "catppuccin_frappe_plus"

[editor]
line-number = "absolute"
mouse = true
color-modes = true
bufferline = "always"
undercurl = true
shell = ["zsh", "-c"]
end-of-line-diagnostics = "hint"
# [editor.inline-diagnostics]
# cursor-line = "warning"
[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "warning"
other-lines = "disable"
prefix-len = 3
[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "diagnostics",
  "workspace-diagnostics",
  "version-control",
  "read-only-indicator",
  "file-modification-indicator",
]
right = [
  "file-type",
  "separator",
  "selections",
  # "register",
  "position",
  # "position-percentage",
  "total-line-numbers",
  "separator",
  "file-encoding",
  "file-line-ending",
]
separator = "•"
mode.normal = " "
mode.insert = " "
mode.select = " "
# end-of-line-diagnostics = "hint"
[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
[editor.lsp]
display-inlay-hints = true
display-messages = true
[editor.gutters.line-numbers]
min-width = 1
[keys.normal]
"C-q" = ":bc"
"C-j" = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- zsh -c -i ~/.config/helix/yazi-picker.sh"
# "C-j" = [":new", ":insert-output yazi", ":buffer-close!", ":redraw"]
"C-l" = ":sh zellij run -f -x 15% -y 15% --width 70% --height 70% -- zsh -c -i ~/.config/helix/lazygit-popup.sh"
# "C-l" = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
# "C-f" = ":sh zellij run -f -x 15% -y 15% --width 70% --height 70% -- bash ~/.config/helix/serpl-popup.sh"
# "C-f" = [":new", ":insert-output serpl", ":buffer-close!", ":redraw"]
# "C-v" = [":new", ":insert-output yazi", ":buffer-close!", ":redraw"]
# "C-v" = ":sh zellij run -f -x 15% -y 15% --width 70% --height 70% -- bash ~/.config/helix/broot-popup.sh"
"S-left" = ":bp"
"S-right" = ":bn"
"A-k" = "rotate_view"
"A-j" = "rotate_view_reverse"
"S-down" = "buffer_picker"
"S-up" = "file_picker"
"S-esc" = ["collapse_selection", "keep_primary_selection"]
"f" = { "s" = "symbol_picker", "S" = "workspace_symbol_picker", "z" = "global_search" }

"A-right" = "move_next_word_start"
"A-left" = "move_prev_word_end"
# "S-A-l" = "move_next_word_start"
# "S-A-h" = "move_prev_word_end"

# "A-f" = ":pipe prettier COMPLETE THIS"
# Moving lines
# "A-down" = ["extend_line_below","delete_selection","paste_clipboard_after"] 
# "A-up" = ["extend_line_below","delete_selection","move_line_up","paste_clipboard_before"] 
[keys.insert]
"S-A-s" = ["normal_mode", ":w"]
"C-n" = ":n"
"C-q" = ":bc"
"C-a" = "normal_mode"
"A-right" = "move_next_word_start"
"A-left" = "move_prev_word_end"
