
[default] # a prompt is a section
api = "openai"                          # must refer to an entry in the `.api_configs.toml` file
model = "meta-llama/llama-4-scout:free" # each prompt may define its own model

[[default.messages]] # then you can list messages
role = "system"
content = """\
You are an expert programmer and a shell master. You value code efficiency and clarity above all things. \
What you write will be piped in and out of cli programs so you do not explain anything unless explicitely asked to. \
Never write ``` around your answer, provide only the result of the task you are given. Preserve input formatting.\
"""

[empty] # always nice to have an empty prompt available
api = "openai"
# not mentioning the model will use the default from the api config
messages = []

[test]
api = "openai"
temperature = 0.0

[[test.messages]]
role = "system"
content = """\
You are an expert programmer and a shell master. You value code efficiency and clarity above all things. \
What you write will be piped in and out of cli programs so you do not explain anything unless explicitely asked to. \
Never write ``` around your answer, provide only the result of the task you are given. Preserve input formatting.\
"""

[[test.messages]]
role = "user"
# the following placeholder string #[<input>] will be replaced by the input
# each message seeks it and replaces it
content = '''Write tests using pytest for the following code. Parametrize it if appropriate.

#[<input>]
'''
[commit] # a prompt is a section
api = "openai"                          # must refer to an entry in the `.api_configs.toml` file
model = "meta-llama/llama-4-scout:free" # each prompt may define its own model
# api = "cerebras"                          # must refer to an entry in the `.api_configs.toml` file
# model = "llama-4-scout-17b-16e-instruct	" # each prompt may define its own model

[[commit.messages]] # then you can list messages
role = "system"
content = """\
You are a git master. You generate git commit messages based on the diff given. \
What you write will be used as git commit message. \
Use commit convetions \
<type>[optional scope]: <description>\
[optional body]\
[optional footer(s)]\
Example: \
fix: prevent racing of requests\
\
Introduce a request id and a reference to latest request. Dismiss\
incoming responses other than from latest request.\
\
Remove timeouts which were used to mitigate the racing issue but are\
obsolete now.\
\
Reviewed-by: Z\
Refs: #123\
\
Never write ``` around your answer, provide only the result of the task you are given. Preserve input formatting.\
"""
